// Code generated by "stringer -output consts_string_test.go -type CellType -trimprefix CellType"; DO NOT EDIT.

package excelize_test

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CellTypeUnset-0]
	_ = x[CellTypeBool-1]
	_ = x[CellTypeDate-2]
	_ = x[CellTypeError-3]
	_ = x[CellTypeFormula-4]
	_ = x[CellTypeInlineString-5]
	_ = x[CellTypeNumber-6]
	_ = x[CellTypeSharedString-7]
}

const _CellType_name = "UnsetBoolDateErrorFormulaInlineStringNumberSharedString"

var _CellType_index = [...]uint8{0, 5, 9, 13, 18, 25, 37, 43, 55}

func (i CellType) String() string {
	if i >= CellType(len(_CellType_index)-1) {
		return "CellType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CellType_name[_CellType_index[i]:_CellType_index[i+1]]
}
