// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: cancel.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Cancel_IWillCancel_FullMethodName = "/cancel.Cancel/IWillCancel"
)

// CancelClient is the client API for Cancel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CancelClient interface {
	IWillCancel(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type cancelClient struct {
	cc grpc.ClientConnInterface
}

func NewCancelClient(cc grpc.ClientConnInterface) CancelClient {
	return &cancelClient{cc}
}

func (c *cancelClient) IWillCancel(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Cancel_IWillCancel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CancelServer is the server API for Cancel service.
// All implementations must embed UnimplementedCancelServer
// for forward compatibility
type CancelServer interface {
	IWillCancel(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedCancelServer()
}

// UnimplementedCancelServer must be embedded to have forward compatible implementations.
type UnimplementedCancelServer struct {
}

func (UnimplementedCancelServer) IWillCancel(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IWillCancel not implemented")
}
func (UnimplementedCancelServer) mustEmbedUnimplementedCancelServer() {}

// UnsafeCancelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CancelServer will
// result in compilation errors.
type UnsafeCancelServer interface {
	mustEmbedUnimplementedCancelServer()
}

func RegisterCancelServer(s grpc.ServiceRegistrar, srv CancelServer) {
	s.RegisterService(&Cancel_ServiceDesc, srv)
}

func _Cancel_IWillCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CancelServer).IWillCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cancel_IWillCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CancelServer).IWillCancel(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Cancel_ServiceDesc is the grpc.ServiceDesc for Cancel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cancel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cancel.Cancel",
	HandlerType: (*CancelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IWillCancel",
			Handler:    _Cancel_IWillCancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cancel.proto",
}
