definitions:
  main.queryReq:
    properties:
      age:
        type: integer
      phone:
        type: string
    type: object
  main.queryRsp:
    properties:
      age:
        type: integer
      height:
        type: integer
      phone:
        type: string
    type: object
  main.request:
    properties:
      data:
        description: 不同请求对应的请求包体
      sid:
        description: 请求的 session ID，如果是登录用户需要带上
        type: string
      source:
        description: 请求来源，h5
        type: string
      user_id:
        description: 用户 ID
        example: "0"
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/account/change_pwd:
    post:
      parameters:
      - description: 请求参数
        in: body
        name: data
        required: true
        schema:
          allOf:
          - $ref: '#/definitions/main.request'
          - properties:
              data:
                $ref: '#/definitions/main.queryReq'
            type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.queryRsp'
      summary: 管理员更改自己密码
      tags:
      - h5
  /foo/bar/foo/bar:
    post:
      parameters:
      - description: 请求参数
        in: body
        name: data
        required: true
        schema:
          allOf:
          - $ref: '#/definitions/main.request'
          - properties:
              data:
                $ref: '#/definitions/main.queryReq'
            type: object
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.queryRsp'
      summary: 创建创作参考
      tags:
      - 创作参考
swagger: "2.0"
